export const GETCURRENTLOCATION = "GETCURRENTLOCATION";
export const GETWEATHERDATA = "GETWEATHERDATA";
export const GETAUTOCOMPLETEDATA = "GETAUTOCOMPLETEDATA";
export const GETHISTORYDATA = "GETHISTORYDATA";
export const SETSUCCESSMESSAGE = "SETSUCCESSMESSAGE";
export const SETERRORMESSAGE = "SETERRORMESSAGE";
